M48
; DRILL file {KiCad 6.0.4-6f826c9f35~116~ubuntu20.04.1} date mié 01 jun 2022 18:14:02
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-01T18:14:02+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-6f826c9f35~116~ubuntu20.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
%
G90
G05
T1
X6.0Y-2.95
T2
X6.35Y-3.45
X6.35Y-3.85
T3
X6.25Y-2.95
X6.35Y-2.95
T0
M30
